### ISSUE TITLE
Prevent negative integers from being entered to Calculator

### ISSUE THREAD

**Issue by Rha02** [JobFishermen/lagoon#5]
As of right now, there is no validation for entering negative integers for the Quantity/Weight/Gaylords field.

**Comment by soundy0115** [comment]
Will we throw any exception to prevent any invalid inputs?

**Comment by Rha02** [comment]
Not necessarily. We could set it to zero if it goes below zero.

**Comment by soundy0115** [comment]
When I try to put the negative sign, it prevents it.
However **when I click the downward button** in the `Quantity` section, **it goes down to negative**, and I also can add it to the calculation.
![Screen Shot 2023-03-30 at 12 28 12 AM](https://user-images.githubusercontent.com/69425103/228761777-39e03912-d6c0-41c7-86fe-385970d5e6b5.png)
